sudo: false
language: erlang
before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
script: ./rebar3 ct
notifications:
  disabled: true
otp_release:
  - 18.3
  - 18.0
  - 17.5
  - 17.1
